version: '3.7'

networks:
  openchat:

volumes:
  # Mount your current directory as a shared volume, but mount a persistent docker volume in place of local node_modules and vendor directories.
  # This will allow node_modules and vendor to persist between `docker-compose up` runs.
  vendor:
  node_modules:
  db_data:

services:
  # ========================
  # Web Server
  # ========================
  nginx:
    image: nginx:stable-alpine
    container_name: oc-nginx
    ports:
      - 8888:80
    volumes:
      - .:/var/www/html
      - ./docker/config/nginx/:/etc/nginx/conf.d/:ro
      - vendor:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules
    depends_on:
      - app
    networks:
      - openchat

  # ========================
  # Database
  # ========================
  db:
    image: mysql:5.7
    container_name: oc-db
    restart: unless-stopped
    tty: true
    ports:
      - 33061:3306
    environment:
      # `secret` as password is used only in local development.
      MYSQL_ROOT_PASSWORD: secret
      # The application db user can't be named `root`.
      MYSQL_USER: ${DB_USER} # Requires that `DB_USER` has been defined.
      MYSQL_PASSWORD: ${DB_PASSWORD} # Requires that `DB_PASSWORD` has been defined.
      MYSQL_DATABASE: ${DB_NAME} # Requires that `DB_NAME` has been defined.
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/:/docker-entrypoint-initdb.d/
    networks:
      - openchat

  # ========================
  # Application
  # ========================
  app:
    image: app
    container_name: oc-app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - vendor:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules
    ports:
      - 9000:9000 # 9000 on the host map to 9000 on the container, make sure is not in use
    depends_on:
      - db
    networks:
      - openchat